package peering

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	contractpeering "github.com/hero-engine/hero/contracts/peering"
	"github.com/hero-engine/hero/internal/config"
	"github.com/hero-engine/hero/internal/gitutil"
	"github.com/hero-engine/hero/internal/spec"
)

// PeerManifestFileName is the relative path under the hero workspace
// where the manifest is written.
const PeerManifestFileName = "peer-manifest.yaml"

// GenerateManifest produces this workspace's peer manifest from the
// local conventions + hero.json peering config. Default publish set
// is empty: only conventions explicitly marked peer-surface (via
// convention frontmatter `peer: true` or via the workspace-level
// publish_conventions list) appear.
//
// Idempotent and pure aside from the disk read of conventions.
func GenerateManifest(projectRoot string) (*contractpeering.PeerManifest, error) {
	cfg, err := config.Load(projectRoot)
	if err != nil {
		return nil, fmt.Errorf("load config: %w", err)
	}
	if cfg.PeerID == "" {
		return nil, fmt.Errorf("workspace has no peer_id — run `hero` once to mint")
	}
	heroDir := cfg.HeroDir(projectRoot)

	// Prefer the committed, worktree-invariant hero.json:name. Workspaces
	// from before `name` was minted at `hero init` have none, so fall back
	// to a live directory lookup — but resolve through gitutil.RepoRoot
	// first, so that fallback lands on the main checkout's directory
	// instead of a linked worktree's own (often unrelated) basename.
	name := cfg.Name
	if name == "" {
		name = filepath.Base(gitutil.RepoRoot(projectRoot))
	}

	manifest := &contractpeering.PeerManifest{
		Schema:           1,
		ContractsVersion: contractpeering.PeeringContractsVersion,
		Repo: contractpeering.RepoIdentity{
			PeerID: cfg.PeerID,
			Name:   name,
		},
		GeneratedAt: time.Now().UTC(),
	}
	if cfg.Peering != nil {
		if cfg.Peering.Display != "" {
			manifest.Repo.Display = cfg.Peering.Display
		}
		if cfg.Peering.ScopeHint != "" {
			manifest.Repo.ScopeHint = cfg.Peering.ScopeHint
		}
	}

	// Build the explicit publish set: configured globs + per-spec
	// frontmatter peer: true. Default empty.
	publishGlobs := []string{}
	if cfg.Peering != nil {
		publishGlobs = append(publishGlobs, cfg.Peering.PublishConventions...)
	}

	specs, err := spec.Discover(heroDir)
	if err != nil {
		return nil, fmt.Errorf("discover specs: %w", err)
	}
	for _, s := range specs {
		if s.Type != spec.TypeConvention {
			continue
		}
		if !isPeerSurface(s, publishGlobs) {
			continue
		}
		entry := contractpeering.ConventionEntry{
			Slug:    s.Slug,
			Title:   s.Title,
			Surface: s.Tags, // tags double as surface labels until we add a dedicated field
			Path:    relPathOrFull(heroDir, s.Path),
			Digest:  digestFile(s.Path),
		}
		manifest.Conventions = append(manifest.Conventions, entry)
	}
	sort.Slice(manifest.Conventions, func(i, j int) bool {
		return manifest.Conventions[i].Slug < manifest.Conventions[j].Slug
	})

	return manifest, nil
}

// WriteManifest serializes a manifest as YAML to
// `<heroDir>/peer-manifest.yaml`. Skips the write when only the
// generated_at timestamp changed.
func WriteManifest(heroDir string, m *contractpeering.PeerManifest) error {
	if err := os.MkdirAll(heroDir, 0o755); err != nil {
		return err
	}
	target := filepath.Join(heroDir, PeerManifestFileName)

	data, err := yaml.Marshal(m)
	if err != nil {
		return fmt.Errorf("marshal manifest: %w", err)
	}
	header := "# Generated by `hero index` — do not hand-edit.\n" +
		"# Peer manifest published to sibling Hero workspaces.\n"
	newContent := append([]byte(header), data...)

	if existing, readErr := os.ReadFile(target); readErr == nil {
		if stripGeneratedAt(string(existing)) == stripGeneratedAt(string(newContent)) {
			return nil
		}
	}

	tmp := target + ".tmp"
	if err := os.WriteFile(tmp, newContent, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, target)
}

var reGeneratedAt = regexp.MustCompile(`(?m)^generated_at: .+$`)

func stripGeneratedAt(s string) string {
	return reGeneratedAt.ReplaceAllString(s, "generated_at: <stripped>")
}

// GenerateAndWriteManifest is the convenience entry point called by
// `hero index`. Best-effort: missing peer_id returns nil without
// writing.
func GenerateAndWriteManifest(projectRoot string) error {
	cfg, err := config.Load(projectRoot)
	if err != nil {
		return err
	}
	if cfg.PeerID == "" {
		return nil
	}
	m, err := GenerateManifest(projectRoot)
	if err != nil {
		return err
	}
	return WriteManifest(cfg.HeroDir(projectRoot), m)
}

// isPeerSurface reports whether a convention should appear in the
// peer manifest. Two opt-in mechanisms:
//
//  1. The convention's frontmatter sets `peer: true` (recorded as a
//     tag during parsing — we treat the "peer-surface" tag as the
//     positive signal until a dedicated field lands).
//  2. The workspace config lists the slug (or a glob matching it) in
//     hero.json: peering.publish_conventions.
//
// Default is FALSE — empty publish set.
func isPeerSurface(s *spec.Spec, globs []string) bool {
	for _, tag := range s.Tags {
		if tag == "peer-surface" || tag == "peer" {
			return true
		}
	}
	for _, g := range globs {
		if matchGlob(g, s.Slug) {
			return true
		}
	}
	return false
}

func matchGlob(pattern, candidate string) bool {
	if pattern == candidate {
		return true
	}
	ok, err := path.Match(pattern, candidate)
	if err != nil {
		return false
	}
	return ok
}

// digestFile produces a short content digest for the manifest's
// digest field. Format: "sha256:<first-12-hex-chars>".
func digestFile(p string) string {
	data, err := os.ReadFile(p)
	if err != nil {
		return ""
	}
	sum := sha256.Sum256(data)
	return fmt.Sprintf("sha256:%x", sum[:6])
}

// relPathOrFull returns the path relative to heroDir, or the original
// path when it isn't under heroDir.
func relPathOrFull(heroDir, p string) string {
	if rel, err := filepath.Rel(heroDir, p); err == nil && !strings.HasPrefix(rel, "..") {
		return filepath.Join(filepath.Base(heroDir), rel)
	}
	return p
}
